### ISSUE TITLE
باقی ماندن کلمه جستجو شده

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#100]
تا زمانی که صفحه سایت رفرش نشود کلمه جستجو شده در سرچ بار باقی می ماند مگر اینکه دسته بندی خاصی از نوار دسته بندی بالای سایت انتخاب شود.

**Comment by milad7212** [comment]
تا زمانی فرد  کلمه ای رو سرچ کرده باشه داخل اینپوت نمایش داده میشه.  الان اگه رفرش هم انجام بشه مجدد نمایش داده میشه که بنظرم درسته مجدد بعد از بررسی اگه ایرادی بود بفرمایید. 
@MaryamSamareh

**Comment by MaryamSamareh** [comment]
@milad7212 
لطفا دکمه ضربدر در سرچ بار برای حذف کلمه جستجو شده قرار بدهید.

**Comment by milad7212** [comment]
@MaryamSamareh  
محل قرار دادن دکمه ضربدر کجا باشه .خواست بجای آیکون سرچ بذارم که جالب نبود.نظر شما چیه؟

**Comment by milad7212** [comment]
این قابلیت اضافه شد
