### ISSUE TITLE
انتخاب از لیست محصولات مشابه

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#101]
اگر از لیست محصولات مشابه، محصول دیگری از حجره ای دیگر انتخاب شود در لیست "محصولات دیگر حجره"، همچنان محصولات حجره قبلی نمایش داده می شود تا زمانی که صفحه رفرش شود. برای مثال من ابتدا محصولی از نیل مارکت انتخاب کرده ام و سپس از لیست محصولات مشابه، محصولی از آزادی استور انتخاب کرده ام. اما در لیست "محصولات دیگر آزادی استور" همچنان محصولات نیل مارکت نمایش داده می شود. تا زمانی که صفحه رفرش نشود لیست محصولات مشابه هم آپدیت نمی شود.

**Comment by milad7212** [comment]
این مشکل قبلا حل شده است.
