### ISSUE TITLE
دکمه عقب جلو کردن عکس ها

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#102]
بهتر است در دو طرف عکس ها دکمه های جهت نما برای دیدن عکس قبل و بعد وجود داشته باشد. یا با دکمه های جهت نمای کیبورد این امکان فراهم شود (اگر با هر دو باشد بسیار بهتر و راحت تر است)

**Comment by sahar-shafiee** [comment]
@saman7799 @MaryamSamareh 
بی زحمت وقتی ایشویی ثبت می شود لطفا توضیحات کامل نوشته شود که در کدام صفحه این مسئله دیده شده و اگر عکسی موجود هست لطفا عکس نیز قرار داده شود

**Comment by saman7799** [comment]
@sahar-shafiee 
منظور از عکس ها ، عکس های موجود در صفحه محصولات هست.

**Comment by milad7212** [comment]
برای جابجایی عکس دکمه اضافه گردید
