### ISSUE TITLE
اپدیت تنظیمات حجره

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#11]
هر بخشی از تنظیمات حجره را که اپدیت میکنیم هیچکدام ذخیره نمی شود.( ارور به هنگام به روز رسانی تنظیمات حجره)

**Comment by milad7212** [comment]
- [ ]

**Comment by milad7212** [comment]
##  I checked and didn't see this error. After reviewing Ms.Hashemi, I will review it again

**Comment by sahar-shafiee** [comment]
@MaryamSamareh 
من با خانم هاشمی در این مورد صحبت کرده ام گفتند که تست شده و این مسئله حل شده برای همین من این ایشو رو میبندم
