### ISSUE TITLE
قرار دادن دسته بندی ها در وسط هدر

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_frontend#113]
دسته بندی ها بعد از اخرین تغییرات وسط قرار نمیگیرند

**Comment by MaryamSamareh** [comment]
لطفا اگر امکان نمایش تمام دسته بندی های سایت وجود دارد در سمت راست صفحه قرار بگیرند اما اگر همه نمایش داده نمی شوند وسط صفحه باشند.
@sahar-shafiee @milad7212
