### ISSUE TITLE
فرستادن  ایدی  برای اپدیت شهر

### ISSUE THREAD

**Issue by milad7212** [nakhll-company/nakhll_frontend#114]

**Comment by sahar-shafiee** [comment]
@milad7212 لطفا روی ایشو توضیح بنویسید که مشخص بشه دقیقا چهکاری در حال انجام است

**Comment by milad7212** [comment]
@likecodingloveproblems  در بک این موضوع به نتیجه ای رسید؟

**Comment by likecodingloveproblems** [comment]
@milad7212 لطفا ای پی آی رو مشخص کنید.

**Comment by likecodingloveproblems** [comment]
تا اونجایی که خاطرم هست توی یکی از ای پی آی ها فقط اسم استان و شهرستان و شهر فرستاده می شود و می تونه ارور برگردونه.

**Comment by milad7212** [comment]
اگر منظور این تسک در صفحه ایجاد حجره هست .توسط خانم شفیعی انجام شده است
@likecodingloveproblems 
@sahar-shafiee

**Comment by milad7212** [comment]
@sahar-shafiee 
خانم شفیعی این تسک توسط شما حل شده است. در صورت تایید این تسک را ببنید.
