### ISSUE TITLE
نمایش 0 درصد تخفیف

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#116]
بعضی محصولات قیمت قبل و بعد از تخفیفشان یکسان است و درصد تخفیف را برای آنها صفر نمایش می دهد. اگر محصولی قیمت قبل و بعد از تخفیفش یکسان بود فقط یک قیمت برای آن نمایش داده شود.

**Comment by milad7212** [comment]
Done
