### ISSUE TITLE
نمایش قیمت بدون تخفیف

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#123]
زمانی که محصولی فقط یک قیمت دارد (تخفیف ندارد) بهتر است قیمت قبل آن که 0 نوشته شده در حالت hide قرار بگیرد و چیزی نمایش داده نشود.

**Comment by milad7212** [comment]
این مورد در کارت محصولات درست شد و در صفحه پروداکت   در دسکتاپ نمایش داده میشد .که آن هم درست شد

**Comment by sahar-shafiee** [comment]
@milad7212 لطفا برای حالت گوشی نیز اضافه شود

**Comment by milad7212** [comment]
در برنچ 102 اضافه شد .
