### ISSUE TITLE
دکمه خرید در زمان موجود نبودن محصول

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#124]
زمانی که محصولی موجود نیست بهتر است دکمه خرید غیر فعال شود. زیرا به دلیل بزرگتر بودن دکمه خرید ابتدا خریدار آن را می بیند و ممکن است متوجه موجود نبودن آن محصول نشود.

**Comment by milad7212** [comment]
این مورد انجام شده است.
فقط در صفحه های لندینگ به این علت که در زمان ساخت بصورت استاتیکی صفحه ساخته میشود. در ان زمان اگر کالا موجود باشد . دکمه خرید وجود دارد در کارت محصول . و اگر محصول بعدا ناموجود شود. این دکمه باقی خواهد ماند.ایشو این مورد در بک زده شده و  در فرانت نیازمنده تغییرات کلی در صفحه لایو ادیت هست. و بعد از تغییرات  صفحاتی که با سیستم قبلی   ساخته شدند باید از اول ساخته شود.
@likecodingloveproblems
