### ISSUE TITLE
نمایش پیغام در هنگام اضافه کردن محصول به سبد خرید

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#125]
پس از اضافه کردن محصولات به سبد خرید، بهتر است جمله ی "داده ها با موفقیت ثبت شدند" با جمله ای مانند "محصول انتخابی به سبد خرید شما اضافه شد" جایگزین شود.

**Comment by milad7212** [comment]
![localhost_3007_search__q=%D9%84%D8%A8%D8%A7%D8%B3 (4)](https://user-images.githubusercontent.com/25881604/172762615-6178a619-9ccc-462f-85f0-92bec00fc297.png)
قبلا رانجام شده است
