### ISSUE TITLE
نمایش محصولات در سبد خرید

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#126]
اگر محصولی در سبد خرید وجود داشته باشد در اولین بار ورود به صفحه و قبل از رفرش یا قبل از ورود به سبد خرید، تعداد محصولاتی که در سبد خرید است به صورت عدد کوچک بالای لوگوی آن نمایش داده نمی شود

**Comment by milad7212** [comment]
@saman7799 
این مورد قبلا حل شده است.
