### ISSUE TITLE
نمایش درصد تخفیف

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#138]
درصد تخفیف در صفحه محصول نمایش داده نمی شود.

**Comment by milad7212** [comment]
![Uploading localhost_3007_shop_yaskala_product_yas-xtw-te72_.png…]()
@MaryamSamareh 
خانم هاشمی من در جانمایی درصد موفق نبود .شما بفرمایید کجا بذارمش

**Comment by MaryamSamareh** [comment]
![image](https://user-images.githubusercontent.com/48446254/177024145-d682e607-5430-44fd-9114-e398af9f2e76.png)
سمت چپ قیمت قبل، فونت هم سایز با فونت قیمت قبل از تخفیف و در یک مربع با border radius 8
@milad7212

**Comment by MaryamSamareh** [comment]
![image](https://user-images.githubusercontent.com/48446254/177024204-65d7794d-4880-4052-adcf-7d624db66379.png)
لطفا برای حفظ یکپارچگی، تمام بخش هایی که درصد تخفیف را نمایش می دهند شبیه به این قسمت که طراحی کردم بشوند. علامت درصد در سبد خرید هم برعکس است (پشت عدد است) که برای اعداد فارسی باید جلوی عدد قرار بگیرد.
کد رنگ قرمز: C73A27
