### ISSUE TITLE
پیغام زمان حذف محصول

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#139]
با حذف محصول از سبد خرید با دکمه کاهش تعداد (دکمه منفی) بهتر است جمله ی "داده ها با موفقیت ثبت شدند" با جمله "محصول از سبد خرید حذف شد" جایگزین شود.

**Comment by milad7212** [comment]
![localhost_3007_cart_ (1)](https://user-images.githubusercontent.com/25881604/173224410-058e4044-6a02-4999-9971-ca080ccadfe4.png)
@MaryamSamareh 
@saman7799 
Done
