### ISSUE TITLE
دکمه حذف محصول

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#140]
وجود دو دکمه برای حذف از سبد خرید لازم نیست (علامت ضربدر و علامت منفی) و بهتر است تنها یکی از آنها باشد.
زمانی که فقط یک عدد از یک محصول در سبد خرید وجود دارد بهتر است دکمه علامت منفی به ضربدر یا سطل آشغال تبدیل شود که کاربر متوجه شود با کلیک بر روی آن، محصول از سبد خرید حذف خواهد شد.

**Comment by milad7212** [comment]
@MaryamSamareh 
@saman7799 
در تسک 139 گفته شده بود پیام حذف وقتی روی دکمه منفی زده میشه عوض بشه .اگه این تسک برای حذف دکمه مطرح شده . تعریف آن تسک جایگاهی نداشت

**Comment by milad7212** [comment]
@MaryamSamareh 
خانم هاشمی این تسک را بررسی میکنید. ایا نیاز هست انجام شود ؟

**Comment by MaryamSamareh** [comment]
> @MaryamSamareh خانم هاشمی این تسک را بررسی میکنید. ایا نیاز هست انجام شود ؟

خیر فعلا نیاز نیست
