### ISSUE TITLE
دکمه افزایش تعداد محصول

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#141]
دکمه افزایش تعداد محصول بهتر است به رنگ سبز در بیاید.

**Comment by milad7212** [comment]
@MaryamSamareh 
کد رنگی را میفرستید؟

**Comment by milad7212** [comment]
@MaryamSamareh

**Comment by MaryamSamareh** [comment]
> @MaryamSamareh کد رنگی را میفرستید؟
@milad7212 
1D943C

**Comment by milad7212** [comment]
تغییر رنگ صورت گرفت.
