### ISSUE TITLE
قیمت تکی محصولات در سبد خرید

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#142]
قیمت تکی هر محصول هم در سبد خرید نمایش داده شود (زمانی که تعداد محصولی را افزایش بدهیم فقط قیمت مجموع کالاها نمایش داده می شود).

**Comment by milad7212** [comment]
![localhost_3007_cart_](https://user-images.githubusercontent.com/25881604/173221783-42a01ff5-0090-4850-944e-1ca37035fdd0.png)
@MaryamSamareh 
تغییر به این صورت انجام شد .اگه جایی نیاز به تغییر داشت . مطرح کنید
