### ISSUE TITLE
صفحه ویرایش آدرس در فرآیند خرید

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#143]
در صفحه ویرایش آدرس،  در فرآیند خرید زمانی که گزینه "بازگشت" انتخاب می شود بهتر است هشداری مانند "آیا از ذخیره نکردن تغییرات خود مطمئن هستید" نمایش داده شود تا کاربر بداند که با کلیک روی این گزینه همه تغییرات از بین می روند.
وجود دو دکمه ی بازگشت در صفحه غیر ضروری است و بهتر است فقط یکی از آنها باقی بماند.
در صفحه ویرایش آدرس، در فرآیند خرید تا زمانی که استان را تغییر ندهیم امکان تغییر شهرستان و شهر وجود ندارد و گزینه های آن ها را نمایش نمی دهد.
اگر سایز صفحه نمایش کوچک باشد و آدرس طولانی باشد، در برخی اندازه ها آدرس از کادر بیرون می زند. مثلا در سایز صفحه نمایش 593 پیکسل

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh لطفا راه حل ها رو مشخص تر بنویسید.

- [ ] در صفحه ویرایش آدرس، در فرآیند خرید زمانی که گزینه "بازگشت" انتخاب می شود بهتر است هشداری مانند "آیا از ذخیره نکردن تغییرات خود مطمئن هستید" نمایش داده شود تا کاربر بداند که با کلیک روی این گزینه همه تغییرات از بین می روند.
وجود دو دکمه ی بازگشت در صفحه غیر ضروری است و بهتر است فقط یکی از آنها باقی بماند.
- [ ] در صفحه ویرایش آدرس، در فرآیند خرید تا زمانی که استان را تغییر ندهیم امکان تغییر شهرستان و شهر وجود ندارد و گزینه های آن ها را نمایش نمی دهد.
- [ ] اگر سایز صفحه نمایش کوچک باشد و آدرس طولانی باشد، در برخی اندازه ها آدرس از کادر بیرون می زند. مثلا در سایز صفحه نمایش 593 پیکسل

**Comment by likecodingloveproblems** [comment]
@saman7799 لطفا تسک ها را تا حد ممکن کوچک کنید.

**Comment by saman7799** [comment]
این تسک به سه تسک با الویت مختلف تبدیل و در برد فرانت قرار گرفت. بنابراین این ایشو رو من میبندم.
@likecodingloveproblems
