### ISSUE TITLE
قسمت روش ارسال

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#144]
موارد مربوط به قسمت روش ارسال:
- جهت فلش های کنار محصولات برای بازشدن روش ارسال، برعکس است.
- زمانی که روی فلش کلیک می شود بهتر است اسم محصول خریداری شده هم نوشته شود چون ممکن است عکس واضح نباشد یا بعضی محصولات عکس ندارند.
- زمانی که روی فلش کلیک می شود صفحه زیرین سفید است که این احساس را می دهد که از صفحه اصلی جداست. بهتر است همرنگ با کارت محصول (آبی) باشد.
- بهتر است در بخشی که باز می شود به جای "روش: … " نوشته شود "روش ارسال: … " تا ابهام ایجاد نکند.
- هم در کارت محصولات برای هر حجره هزینه ارسال به صورت "مجموع هزینه" نوشته شده و هم در بالای صفحه که جمع کل هزینه های ارسال است. بهتر است اولی به "هزینه ارسال حجره" یا مشابه آن تبدیل شود که باعث ابهام نشود.
- جمله "انتخاب روش ارسال" در وسط صفحه قرار ندارد.

**Comment by likecodingloveproblems** [comment]
این صفحه در مدل سکه با صفحه بعد ترکیب خواهد شد.
