### ISSUE TITLE
ارور انتخاب استان در ویرایش پروفایل

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#15]
1.	در قسمت ویرایش پروفایل، زمانی که استان روی یک مقداری ذخیره شده باشد و سپس آن را تغییر بدهیم و قبل از ذخیره تغییرات، دوباره استان اولیه را انتخاب کنیم ارور 500 می دهد. (فرایند: 
استان انتخابی در پروفایل: کرمان. 	
ویرایش پروفایل
استان: مقدار دیگری به جز کرمان
قبل از ذخیره تغییرات، دوباره تغییر استان به کرمان.

**Comment by milad7212** [comment]
پوریا برای اطلاعات ادرسی نیاز دارم ای پی ای بصورت ایجکت تایتل و ایدی داشته باشم
