### ISSUE TITLE
مشکل آدرس طولانی در صفحه ویرایش آدرس

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#152]
در قسمت ویرایش آدرس در فرآیند خرید اگر سایز صفحه نمایش کوچک باشد و آدرس طولانی باشد، در برخی اندازه ها آدرس از کادر بیرون می زند. مثلا در سایز صفحه نمایش 593 پیکسل

**Comment by MaryamSamareh** [comment]
@sahar-shafiee @milad7212 
لطفا بررسی شود

**Comment by milad7212** [comment]
![localhost_3007_cart_address_](https://user-images.githubusercontent.com/25881604/173998662-0c08523c-6af8-4503-b495-6e5e3cdb6ec5.png)

done

**Comment by milad7212** [comment]
![localhost_3007_cart_address_ (2)](https://user-images.githubusercontent.com/25881604/173999001-21085089-1319-4429-9f2e-3d1a486789ac.png)
Done
@MaryamSamareh
