### ISSUE TITLE
خطای ای پی ای پروفایل

### ISSUE THREAD

**Issue by milad7212** [nakhll-company/nakhll_frontend#158]
https://github.com/nakhll-company/nakhll_backend/issues/194#issuecomment-1156019258

**Comment by milad7212** [comment]
این مشکل برطرف شده . خانم شفیعی شما هم ی تست کنید اگه برطرف شده ببنیدینش

**Comment by sahar-shafiee** [comment]
@milad7212 این مسئله هنوز برطرف نشده من خودم رو اساین کردم

**Comment by milad7212** [comment]
@sahar-shafiee 
ای پی ای کال میشد .به درستی کار میکرد .میشه توضیح بدید در چه حالتی کار نمیکنه؟

**Comment by sahar-shafiee** [comment]
@milad7212 در صورتی که اطلاعات جنسیت و تاریخ تولد وارد نشوند نمی توان عکس را اپدیت کرد و خطای 500 داده میشد

**Comment by milad7212** [comment]
@sahar-shafiee 
لطفا روی برنچ main  بک  و فرانت بررسی بفرمایید .اونجا برطرف شده

**Comment by sahar-shafiee** [comment]
@milad7212 
![Untitled](https://user-images.githubusercontent.com/52815608/173998288-77a938b8-04f9-4a2c-a74a-2c1ea99bed05.png)

**Comment by milad7212** [comment]
این مشکل هم در لوکال هم سرور تست شد و مشکلی نداشت به همین دلیل بسته میشود
