### ISSUE TITLE
ناموجود شدن محصولات صفحه لندینگ

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#173]
محصولاتی که در صفحه لندینگ قرار دارند اگر ناموجود شوند هنوز دکمه خرید آنها باقی می ماند

**Comment by milad7212** [comment]
@MaryamSamareh 
خانم هاشمی این صفحه استاتیکی ساخته شده . شما هر محصولی که مد نظرتون هست بگید با محصولی که میگید عوض کنم

**Comment by milad7212** [comment]
با تغییر محصولات در  تسک 191 این مورد برطرف شد
