### ISSUE TITLE
لطفا ابتدا وارد سایت شوید

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#181]
اگر وارد سایت نشده باشیم در صفحه لندینگ ارور "لطفا ابتدا وارد شوید" نمایش داده می شود ولی اگر در سایت باشیم و Session اکسپایر شود، این ارور در همه صفحات نمایش داده می شود و با کلیک روی پروفایل برای ورود دوباره، ارور 500 می دهد. باید حتما یک بار سایت را رفرش کرد تا بتوانیم دوباره وارد بشویم.

**Comment by milad7212** [comment]
این مشکل در برنچ 151 حل شد .
جهت اطمینان این تسک باز بماند و بعد از چند روز تست اگه ایرادی نداشت بسته شود.
@MaryamSamareh

**Comment by milad7212** [comment]
این ایراد  برطرف شده
