### ISSUE TITLE
خارج نشدن از پیشخوان حجره در تلفن همراه

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#183]
در حالت تلفن همراه دکمه های بالای پیشخوان حجره که برای مشاهده حجره، پروفایل و صفحه اصلی وبسایت هستند کار نمی کنند.
![image](https://user-images.githubusercontent.com/48446254/177246980-5349ec28-0247-4425-b529-00808008eec4.png)

**Comment by milad7212** [comment]
این مشکل حل شد.
