### ISSUE TITLE
شماره تلفن همراه در جزئیات سفارش

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#184]
شماره تلفن همراه در بخش جزئیات سفارش مثل قیمت سه رقم سه رقم جدا می شود.
![image](https://user-images.githubusercontent.com/48446254/177248581-413a9d45-0b26-4148-afbf-7b1c8e911079.png)

**Comment by milad7212** [comment]
این مورد برطرف شد
@MaryamSamareh
