### ISSUE TITLE
جزئیات بیشتر در بخش سفارشات حجره

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#185]
در بخش سفارشات حجره با کلیک روی گزینه "جزئیات بیشتر" یکی از محصولات، جزئیات همه محصولات باز می شوند.
![image](https://user-images.githubusercontent.com/48446254/177250240-ab028817-ffdd-4f6f-b111-2a3a83543e5a.png)

**Comment by milad7212** [comment]
خانم هاشمی این تسک انجام شد.لطفا بررسی بفرمایید .
