### ISSUE TITLE
کار نکردن گزینه "مرتب سازی بر اساس"

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#189]
در صفحه حجره ها، گزینه های "مرتب سازی بر اساس" کار نمی کنند.

**Comment by milad7212** [comment]
@likecodingloveproblems 
اگه ممکنه روی لوکال میخوام حجره ام چندین سفارش داشته باشه که بتونم این صفحه را بررسی کنم
