### ISSUE TITLE
تغییر محصولات صفحه لندینگ

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#191]
لطفا سه حجره بخش حجره داران در صفحه لندینگ را با این سه حجره جدید جایگزین کنید:
[https://nakhll.com/shop/sajadsystem/](url)
حجره سجاد سیستم
[https://nakhll.com/shop/%D8%AC%D9%86%D9%88%D8%A8-%DA%A9%D8%A7%D9%84%D8%A7/](url)
حجره جنوب کالا
[https://nakhll.com/shop/%D9%85%D9%84%D9%84-%D9%85%D8%A7%D8%B1%DA%A9%D8%AA/](url)
حجره ملل مارکت

**Comment by MaryamSamareh** [comment]
به جای دسته بندی محصولات دیجیتال در صفحه لندینگ، لطفا این محصولات از حجره گالری آنتیک 7 جایگزین شوند:
[https://nakhll.com/shop/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%A2%D9%86%D8%AA%DB%8C%DA%A9-7/](url)
لینک حجره گالری آنتیک 7
[https://nakhll.com/shop/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%A2%D9%86%D8%AA%DB%8C%DA%A9-7/product/%D8%AF%D8%B3%D8%AA%D8%A8%D9%86%D8%AF-%D8%AA%DB%8C_1/](url)
[https://nakhll.com/shop/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%A2%D9%86%D8%AA%DB%8C%DA%A9-7/product/%D8%AF%D8%B3%D8%AA%D8%A8%D9%86%D8%AF-%D8%AA%DB%8C/](url)
[https://nakhll.com/shop/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%A2%D9%86%D8%AA%DB%8C%DA%A9-7/product/%DA%AF%D8%B1%D8%AF%D9%86%D8%A8%D9%86%D8%AF-%DA%A9%D8%A7%D8%B1%D8%AA%DB%8C%D8%B1-%D9%86%D9%82%D8%B1%D9%87-%D8%A7-%DB%8C-%D9%85%D8%B1%D8%AF%D8%A7%D9%86%D9%87-%D8%A2%D9%84%D9%88%D9%85%DB%8C%D9%86%DB%8C%D9%88%D9%85%DB%8C-%D8%A8%D8%A7%D8%B1%DB%8C%DA%A9/](url)
[https://nakhll.com/shop/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%A2%D9%86%D8%AA%DB%8C%DA%A9-7/product/%D8%B3%D8%AA-%DA%AF%D8%B1%D8%AF%D9%86%D8%A8%D9%86%D8%AF-%D9%88-%D8%AF%D8%B3%D8%AA%D8%A8%D9%86%D8%AF-%DA%A9%D8%A7%D8%B1%D8%AA%DB%8C%D8%B1-%D9%85%D8%B1%D8%AF%D8%A7%D9%86%D9%87-%D9%88-%D8%B2%D9%86%D8%A7%D9%86%D9%87/](url)
[https://nakhll.com/shop/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%A2%D9%86%D8%AA%DB%8C%DA%A9-7/product/%D8%B3%D8%AA%D8%AF%D8%B3%D8%AA%D8%A8%D9%86%D8%AF-%D9%88-%DA%AF%D8%B1%D8%AF%D9%86%D8%A8%D9%86%D8%AF-%DA%A9%D8%A7%D8%B1%D8%AA%DB%8C%D8%B1-%D8%AA%D8%B1%D8%A7%D8%B4-%D8%AE%D9%88%D8%B1%D8%AF%D9%87-%D9%85%D8%B1%D8%AF%D8%A7%D9%86%D9%87-%D9%86%D9%82%D8%B1%D9%87-%D8%A7%DB%8C/](url)
[https://nakhll.com/shop/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%A2%D9%86%D8%AA%DB%8C%DA%A9-7/product/%D8%B3%D8%AA-%D8%AF%D8%B3%D8%AA%D8%A8%D9%86%D8%AF-%D9%88-%DA%AF%D8%B1%D8%AF%D9%86%D8%A8%D9%86%D8%AF-%DA%A9%D8%A7%D8%B1%D8%AA%DB%8C%D8%B1-%D9%86%D9%82%D8%B1%D9%87-%D8%A7%DB%8C-%D9%85%D8%B1%D8%AF%D8%A7%D9%86%D9%87-%D8%B1%D9%86%DA%AF-%D8%AB%D8%A7%D8%A8%D8%AA/](url)

**Comment by MaryamSamareh** [comment]
و به جای محصولات گیاهان دارویی خاتم، این محصولات از حجره قطعات لوازم خانگی جایگزین شوند:
[https://nakhll.com/shop/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C/](url)
لینک حجره قطعات لوازم خانگی
[https://nakhll.com/shop/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C/product/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C-1316-%D9%BE%D9%85%D9%BE-%D8%A7%D8%A8-%D8%A7%D8%AA%D9%88-%D9%BE%D8%B1%D8%B3-%D8%A7%D8%B5%D9%84-%D8%A8%D8%A7-%DA%A9%DB%8C%D9%81%DB%8C%D8%AA-22w-%D9%BE%D8%B1%D9%82%D8%AF%D8%B1%D8%AA-%D8%A7%D9%88%D8%B1%D8%AC%DB%8C%D9%86%D8%A7%D9%84-%D9%81%D8%A7%D8%A8%D8%B1%DB%8C%DA%A9/](url)
محصول 1
[https://nakhll.com/shop/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C/product/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C-1880-%DA%AF%DB%8C%D8%B1%D9%87-%D9%82%D9%81%D9%84-%D9%81%DB%8C%D9%84%D8%AA%D8%B1-%D9%87%D9%88%D8%AF-%D9%82%D9%81%D9%84-%D9%81%D8%B4%D8%A7%D8%B1%DB%8C-%D9%81%DB%8C%D9%84%D8%AA%D8%B1-%D9%87%D9%88%D8%AF-%D9%81%D9%84%D8%B2%DB%8C-%D9%81%D8%A7%D8%A8%D8%B1%DB%8C%DA%A9%DB%8C-2-%D8%B9%D8%AF%D8%AF/](url)
محصول 2
[https://nakhll.com/shop/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C/product/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C-1908-%D8%A7%D9%84%D9%85%D9%86%D8%AA-%D8%B3%D8%B4%D9%88%D8%A7%D8%B1-%D8%AC%D8%A7%D9%86%D8%B3%D9%88%D9%86-%D8%A7%D9%88%D8%B1%D8%AC%DB%8C%D9%86%D8%A7%D9%84-%D9%81%D8%A7%D8%A8%D8%B1%DB%8C%DA%A9%DB%8C/](url)
محصول 3
[https://nakhll.com/shop/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C/product/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C-1315-%D9%84%D9%88%D9%84%D9%87-%D8%AE%D8%B1%D8%B7%D9%88%D9%85%DB%8C-%D8%AC%D8%A7%D8%B1%D9%88%D8%A8%D8%B1%D9%82%DB%8C-%D8%A7%D9%84%D8%AC%DB%8C-lg-%D9%81%DB%8C%D8%B4-%D8%AC%D9%84%D9%88-%D8%AE%D8%A7%D8%B5-%D8%A7%D8%B5%D9%84-%D8%A7%D9%88%D8%B1%D8%AC%DB%8C%D9%86%D8%A7%D9%84-%D8%A7%D9%84%D8%AC%DB%8C/](url)
محصول 4
[https://nakhll.com/shop/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C/product/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C-1557-%D8%AA%DB%8C%D8%BA-%D9%85%D8%A7%D8%B4%DB%8C%D9%86-%D9%85%D9%88%D8%B2%D8%B1-%D8%A7%D9%84%D9%85%D8%A7%D9%86%DB%8C-%D8%A7%D8%B5%D9%84-%D9%81%D8%A7%D8%A8%D8%B1%DB%8C%DA%A9%DB%8C-%D8%AA%DB%8C%D8%BA-%DA%A9%D8%A7%D9%85%D9%84-%D9%85%D8%A7%D8%B4%DB%8C%D9%86-%D9%85%D9%88%D8%B2%D8%B1/](url)
محصول 5
[https://nakhll.com/shop/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C/product/%D9%82%D8%B7%D8%B9%D8%A7%D8%AA-%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AE%D8%A7%D9%86%DA%AF%DB%8C-1064-%D9%81%D9%86%D8%B1-%D8%A8%D9%86%D8%AF%D8%A7%D9%86%D8%AF%D8%A7%D8%B2-%D8%A7%D9%88%D8%B1%D8%AC%DB%8C%D9%86%D8%A7%D9%84-%D8%A7%D8%B5%D9%84%DB%8C-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D9%87%D9%85%D9%87-%D8%A8%D9%86%D8%AF%D8%A7%D9%86%D8%AF%D8%A7%D8%B2-%D9%87%D8%A7%DB%8C-%D8%A8%D8%B1%D9%82%DB%8C-3%D8%B9%D8%AF%D8%AF%DB%8C/](url)
محصول 6

**Comment by milad7212** [comment]
Done

**Comment by MaryamSamareh** [comment]
@milad7212 
لطفا به جای یکی از محصولات گالری آنتیک که ناموجود شده، این محصول را جایگزین فرمایید
[https://nakhll.com/shop/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%A2%D9%86%D8%AA%DB%8C%DA%A9-7/product/%D9%BE%D8%A7%D8%A8%D9%86%D8%AF-%D8%A7%D8%B3%D9%BE%D9%88%D8%B1%D8%AA-%D8%A8%D8%AF%D9%88%D9%86-%D9%BE%D9%84%D8%A7%DA%A9/](url)

**Comment by milad7212** [comment]
Done
