### ISSUE TITLE
تغییر ارور ثبت حجره

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#192]
![image](https://user-images.githubusercontent.com/48446254/177521523-93e003cb-f9f5-4a0a-a14f-e12a1c0e60a4.png)
لطفا ارور زمان ثبت نام تکراری برای حجره اصلاح شود

**Comment by milad7212** [comment]
@MaryamSamareh 
این تسک بک اندی هست .

**Comment by milad7212** [comment]
به علت بکی بودن تسک . تسک بسته می شود
