### ISSUE TITLE
عدم نمایش درصد تخفیف

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#195]
در صفحه جزئیات محصول، زمانی که محصولی تخفیف ندارد، جای خالی درصد تخفیف هم نمایش داده نشود
![image](https://user-images.githubusercontent.com/48446254/178090689-095052c1-b8e8-42c6-82c1-7a69aaa87321.png)

**Comment by milad7212** [comment]
Done
