### ISSUE TITLE
unpublish product & shops

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#201]
https://www.figma.com/file/jKa53XGlqqX6EwKty2ctmQ/issue-%23136?node-id=14%3A21
page: unpublish shop & product
لطفا فعلا بخشی که برای توضیحات قرار داده شده را خالی بگذارید تا زمانی که متن نوشته آماده شود.

**Comment by milad7212** [comment]
@likecodingloveproblems 
جهت ای پی ای

**Comment by milad7212** [comment]
@MaryamSamareh 
خانم هاشمی متنش آماده شده است؟

**Comment by milad7212** [comment]
@saman7799 
سمت فرانت تموم شده. فقط ای پی ایش اماده بشه .میتوان فرستاد بالا

**Comment by MaryamSamareh** [comment]
@milad7212 
توضیحات بخش "چرا این اتفاق افتاده است" برای حجره:
-----------------------------------------------------------------
این حجره به یکی از دلایل زیر غیرفعال شده است:
درخواست حجره دار برای غیرفعال سازی حجره 
عدم مسئولیت پذیری و پاسخگویی حجره دار
حجره دار سفارشات خود را به موقع ارسال نمی کرده و یا سفارشات را لغو میکرده است

------------------------------------------------------------------
برای محصول:
------------------------------------------------------------------
این محصول به یکی از دلایل زیر از دسترس خارج شده است:
بر خلاف قوانین نخل و جمهوری اسلامی بوده است
بنا به درخواست فروشنده محصول غیرفعال شده است
