### ISSUE TITLE
موارد اجباری در ذخیره تنظیمات حجره

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#23]
هنگام ذخیره سازی اطلاعات حجره، حتما باید آدرس، کدپستی و کدملی وارد شود و اگر این موارد وارد نشود ارور می دهد.

**Comment by milad7212** [comment]
در ابتدا قرار بود اجباری باشد

**Comment by sahar-shafiee** [comment]
@MaryamSamareh  @likecodingloveproblems 
 لطفا این مورد رو با اقای مهدی زاده بررسی کنید و اگرنیاز به تغییر دارند بفرمایید

**Comment by sahar-shafiee** [comment]
طبق بررسی های خانم هاشمی این موارد باید اجباری باشند. برای همین من این ایشو رو میبندم
