### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#239]
از هر صفحه ای در سایت که روی ورود کلیک کنیم، پس از وارد شدن دوباره به صفحه اصلی هدایت می شویم. اما باید به صفحه ای که از آنجا روی گزینه "ورود به سایت" کلیک کردیم برگردیم.
یعنی مثلا اگر از صفحه حجره روی ورود کلیک کنیم، پس از وارد شدن دوباره به همان صفحه حجره برگردیم.

**Comment by milad7212** [comment]
Done
