### ISSUE TITLE
اسکرول به بالای صفحه در صفحه جزئیات محصول

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_frontend#248]
زمانی که از بین محصولات پیشنهادی در صفحه جزئیات محصول یک محصول انتخاب می شود صفحه اسکرول شده و جزئیات محصول جدید از ابتدای صفحه نمایش داده شود.

**Comment by milad7212** [comment]
با باز شدن در صفحه جدید این مشکل برطرف میشود .بررسی بفرمایید در صورت صلاح تسک را ببندید.
با تشکر
@MaryamSamareh
