### ISSUE TITLE
فیلتر محصولات 

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#260]
در پنل مدیریت حجره داری  فقط فیلتر نام محصول کار میکند و بقیه فیلتر ها کار نمیکنند.

**Comment by milad7212** [comment]
@likecodingloveproblems 
@saman7799 
فیرترهایی که از قبل تعریف شده و پارامترهایی که الان ای پی ای میخواد با هم فرق دارند .اگه امکانش هست کوئری هایی که میگیریند را توضیح دهید

**Comment by milad7212** [comment]
@MaryamSamareh 
خانم هاشمی فیلتر هایی که از نظر شما نیاز هست افزوده بشه یا کاهش یابد را لطفا بفرمایید.
