### ISSUE TITLE
باگ ویرایش محصول نیل مارکت

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#29]
برای ویرایش محصولاتی که عکس ندارند ارور "مشکلی از سمت سرور رخ داده" میدهد اما محصول ویرایش می شود. اگر مدت زمان آماده سازی وارد نمیشد اجازه ویرایش نمیداد اما من با تنظیم این مقدار روی 0 روز توانستم محصول را ویرایش کنم

و اگر در قیمت محصول عدد اعشاری باشد (مثلا قیمت 23000.5 تنظیم شده باشد) اجازه ویرایش تا زمانی که قیمت اصلاح نشده و به صورت عدد صحیح در نیامده نمیدهد

اما در صفحه ویرایش محصولات فقط لیست محصولات 1 تا 50 (صفحه اول) نمایش داده می شود و به دیگر صفحات نمی رود

دسته بندی فعلی محصولات هم نمایش داده نمیشود

**Comment by MaryamSamareh** [comment]
بله همه مواردی که شما ذکر کردید درست هستند و فقط همان مشکل دسته بندی هنوز حل نشده 
@sahar-shafiee

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems 
لطفا مقدار null برای دسته بندی محصولات را هرچه سریعتر بررسی کنید که این مسئله هرچه سریعتر برطرف شود

**Comment by sahar-shafiee** [comment]
@MaryamSamareh @likecodingloveproblems 
نال بودن مقدار دسته بندی باید از سمت بک تصحیح شود به همین دلیل من این ایشو رو میبندم اگر نیاز به تغییرات در فرانت داشتیم یک ایشو جدید باز میکنم
