### ISSUE TITLE
Fix some issues in mobile bar

### ISSUE THREAD

**Issue by adelisardo** [nakhll-company/nakhll_frontend#298]
در نوار منو در موبایل دو اشکال وجود دارد:
- عنوان سکه تغییر کند به گنجینه (تغییر اندازه متن و تاثیر گذاری آنرا در نظر بگیرید)
- در شرایطی رنگ متن آیتم های منو به آبی تغییر می کند، این موضوع در ظاهر اشکالاتی را به وجود می آورد.

**Comment by milad7212** [comment]
Done
