### ISSUE TITLE
باگ حذف شدن عکسهای حجره

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#30]
عکس محصولات بعد از بارگذاری و گذشت چند روز حذف شدند و عکس محصولات نیست(حجره نیل مارکت و گالری آنتیک7،سرای مس،کتابرسان)

**Comment by sahar-shafiee** [comment]
این ایشو نیاز به بررسی از سمت بک دارد برای همین من این ایشو رو میبندم
