### ISSUE TITLE
Fix some issues in coin landing page

### ISSUE THREAD

**Issue by adelisardo** [nakhll-company/nakhll_frontend#308]
لطفا این موارد را اصلاح نمایید:
- در صفحه لندینگ سکه در زیر دکمه همین حالا ثبت نام کنید تعداد 502254 نفر به 54 نفر تغییر کند
- در بخش سکه دریافت شده تعداد از 5550452 به165 تغیر کند و تعداد نفرات هم 54

**Comment by milad7212** [comment]
Done
