### ISSUE TITLE
عکس پروفایل حجره دلیت نمی شود و عکس پروفایل حجره در داشبورد به موقع آپدیت نمی شود

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#31]
پروفایل حذف نمی شود اما آپدیت می شود. اما هربار که وارد تنظیماتت حجره بشویم آدرس و کد پستی حذف شده و دوباره باید وارد شود

زمانی که دو حجره داشته باشیم و حجره انتخابی را عوض کنیم، هنوز تصویر پروفایل حجره قبلی نمایش داده می شود (عکس پروفایل حجره به موقع آپدیت نمی شود.)

**Comment by sahar-shafiee** [comment]
#22 یک ایشو مشابه قبلا داشتیم در این مورد برای همین من همه موارد را داخل همان ایشو اضافه کردم. و این ایشو رو close میکنم
