### ISSUE TITLE
باگ صفحه محصولات

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#32]
حجره دار زمانی وارد قسمت پنل کاربری خود می شود و تعداد محصولات بالایی دارد بر اساس تقسیم بندی صفحات،وارد صفحات2به بعد نمی شود و بعد از کلیک کردن صفحات دیگر صفحه بالا میپرد و فقط صفحه اول محصولات نمایش داده می شود.

**Comment by milad7212** [comment]
این باگ حل شده است

**Comment by sahar-shafiee** [comment]
@MaryamSamareh  خانم هاشمی بی زحمت تست میکنید این مسئله رو که اگر انجام شده در انجام شده ها قرار گیرد

**Comment by MaryamSamareh** [comment]
این باگ برطرف شده است

**Comment by sahar-shafiee** [comment]
این ایشو طبق تستی که انجام شده برطرف شده برای همین من ایشو رو میبندم
