### ISSUE TITLE
بررسی تیکتینگ

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#39]

**Comment by milad7212** [comment]
سید گفتند گفتینو رو بررسی کنم بجای هاب اسپات . من گفتینو رو شورع میکنم به بررسی کردند

**Comment by sahar-shafiee** [comment]
@milad7212 شما در حال کار روی این ایشو هستین یا بررسی تمام شده؟

**Comment by milad7212** [comment]
@sahar-shafiee  نه تمام نشده

**Comment by milad7212** [comment]
داکیومنت ای پی ای  گفتینو مطالعه شد .در کال کردن ای پی ای به ایدی چت نیاز داشت که ارسال میکردم ای پی ای کد 200 میداد ولی برای دیتا ارور برمیگرداند.
بنظرم بررسیش به اندازه آشنایی کافیه .اگه نیاز به اجرای طرحی است میتوان طرح زده شود و  سپس اجرایی کنیم

**Comment by likecodingloveproblems** [comment]
لطفا توضحیات این تسک رو کامل کنید. @saman7799
