### ISSUE TITLE
check branches

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_frontend#40]
@milad7212 
لطفا برنچ های : [JustPriceFilter] و [Jwt] و [priceFilter] و [seo] بررسی کنید و هر کدوم که دیگه نیازی بهشون نیست رو حذف کنید

**Comment by milad7212** [comment]
you can delete seo  & priceFilter

**Comment by sahar-shafiee** [comment]
@milad7212 
thank you 
i deleted these branches
and close this issue
