### ISSUE TITLE
ارور لاگین صفحه اصلی

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_frontend#47]
نمایش پیغام لطفا ابتدا وارد شوید برای کاربر وقتی که صفحه اصلی را باز میکند

**Comment by milad7212** [comment]
لطفا تایتل ها مرتبط تر زده بشه
@sahar-shafiee

**Comment by milad7212** [comment]
داخل لوکال درسته .

**Comment by sahar-shafiee** [comment]
@milad7212 
پس چرا روی سرور درست نیست؟
عنوان ایشو با عنوان صفحه ای که مشکل دارد یکی است و بقیه مسائل داخل توضیحات نوشته می شود چون در این صورت عنوان بسیار طولانی می شود
اگر پیشنهاد بهتری دارین بفرمایید

**Comment by milad7212** [comment]
@sahar-shafiee
ارور لاگین صفحه اصلی

**Comment by sahar-shafiee** [comment]
@milad7212 
بی زحمت وضعیت این ایشو مشخص کنید؟
چون هیچ پول ریکوئستکی هم اساین نشده به این ایشو

**Comment by milad7212** [comment]
@sahar-shafiee چندین بار داخل لوکال تست شده و ایرادی نداشته مجدد امروز بررسی میکنم .

**Comment by milad7212** [comment]
این موضوع در دیباگ کردن دیپلوی انجام شد . لطفا در  صورت بررسی  ببندینش

**Comment by milad7212** [comment]
این موضوع حل شده است
