### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_frontend#53]
@milad7212 
بعد از مرج تغییرات استایل امکان بیلد گرفتن وجود ندارد
لطفا بررسی کنید

**Comment by milad7212** [comment]
@sahar-shafiee  امروز بررسی میشود

**Comment by sahar-shafiee** [comment]
> @sahar-shafiee امروز بررسی میشود

در مورد این ایشو دیروز صحبت کردیم چون شما گفتین روی تست هستین من دارم خودم روش کار میکنم
@milad7212

**Comment by milad7212** [comment]
تشکر ازتون .assaign  کنید ممنونتون میشم

**Comment by sahar-shafiee** [comment]
> تشکر ازتون .assaign کنید ممنونتون میشم

@milad7212 بله حتما
