### ISSUE TITLE
نمایش شماره کاربر در هنگام ارسال کد تایید

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#58]
بهتر است شماره ای که کاربر وارد کرده در صفحه ارسال کد تایید نوشته شود تا کاربر بتواند آن را چک کند و در صورتی که اشتباه باشد آن را ویرایش کند. مثلا "کد تایید برای شماره 09123456789 ارسال شد"
 و در پایین صفحه داشته باشیم: "شماره اشتباه است؟ ویرایش شماره"

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh please design it.

**Comment by MaryamSamareh** [comment]
it can look like this:
![image](https://user-images.githubusercontent.com/48446254/169973593-dc623076-0739-431f-980f-fe989ea9c923.png)
and be able to return to previous page by clicking on "edit" to edit the number
@likecodingloveproblems @milad7212

**Comment by MaryamSamareh** [comment]
dark color code: 273238
blue color code: 224D82
