### ISSUE TITLE
انتخاب استان شهرستان و شهر

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#60]
بهتر است گزینه های انتخاب استان، شهرستان و شهر نوشته راهنما داشته باشد تا کاربر از قبل بداند که با کلیک رو هر گزینه چه چیزی را باید انتخاب کند. زیرا اگر از سمت اشتباه (سمت چپ) روی گزینه کلیک کند هیچ چیزی برایش نمایش داده نمی شود (گزینه انتخاب شهر)

**Comment by likecodingloveproblems** [comment]
این مساله باید طراحی فرآیند کاربری داشته باشد.
نیاز است داستان کاربر و تعریف کار انجام شده(Definition of Done) داشته باشد.
فرض اول: اگر کاربر از قبل استان و شهرستان رو انتخاب کرده، و  بعد دوباره وارد این صفحه شود اکنون اگر بر روی هر زیر دسته مانند شهرستان و شهر نیز کلیک میکند باید بصورت جداگانه برای کاربر نمایش داده شود. به این معنی که کاربر مجبور نشود که از ابتدا از استان فرآیند انتخاب را شروع کند.

لطفا اگر موردی به ذهنتون میرسه کامل کنید. @MaryamSamareh

**Comment by MaryamSamareh** [comment]
> این مساله باید طراحی فرآیند کاربری داشته باشد. نیاز است داستان کاربر و تعریف کار انجام شده(Definition of Done) داشته باشد. فرض اول: اگر کاربر از قبل استان و شهرستان رو انتخاب کرده، و بعد دوباره وارد این صفحه شود اکنون اگر بر روی هر زیر دسته مانند شهرستان و شهر نیز کلیک میکند باید بصورت جداگانه برای کاربر نمایش داده شود. به این معنی که کاربر مجبور نشود که از ابتدا از استان فرآیند انتخاب را شروع کند.
> 
> لطفا اگر موردی به ذهنتون میرسه کامل کنید. @MaryamSamareh

بله کاملا درست می فرمایید. من هم همین مورد به ذهنم رسیده بود که باید برای تمام بخش هایی از سایت که انتخاب آدرس داریم اعمال شود. مثل پروفایل->ویرایش پروفایل
پروفایل-> مدیریت حجره -> تنظیمات حجره
سبد خرید -> ویرایش یا ایجاد نشانی

منتها در این اشکال، منظور من در بخش ویرایش پروفایل کاربر بود که در قسمت محل سکونت، تنها سه باکس برای کامل کردن داریم و هیچکدام نوشته ای برای راهنمایی کاربر ندارند و تا زمانی که روی آنها کلیک نشود کاربر متوجه نمی شود که در هر قسمت چه چیزی را باید وارد کند.

**Comment by likecodingloveproblems** [comment]
بله درست می فرمایید @MaryamSamareh

**Comment by milad7212** [comment]
ببخشید این بخش باید به چه صورت پیاده شود .طرح خاصی مد نظرتون هست؟@MaryamSamareh
