### ISSUE TITLE
تاریخ تولد

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#62]
تاریخ تولد تنظیم نمی شود و هربار که وار شود و ثبت اطلاعات هم انتخاب شود، دوباره که برگردی تاریخ تولد حذف شده

**Comment by likecodingloveproblems** [comment]
آیا API کال می شود؟ @milad7212  @sahar-shafiee

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems 
بله ای پی ای کال می شود و تاریخ تولد نیز ارسال میگردد ولی جوابی که از ای پی ای گرفته می شود موقع دریافت داده ها فرمت صحیحی ندارد
![2](https://user-images.githubusercontent.com/52815608/169973154-5ebca010-0197-4501-9394-4c56bd269908.JPG)
![1](https://user-images.githubusercontent.com/52815608/169973158-28f3555b-f541-42de-9b7c-2c94f8f74f54.JPG)

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
اقای منصوری بی زحمت ای پی ای پروفایل رو چک میکنید
تاریخ تولد درست ارسال میشه ولی موقع دریافت دادها صحیح ارسال نمی شود
عکس داده های ارسالی رو بالاتر داخل کامنت گذاشتم

**Comment by PouryaMansouri** [comment]
چه api رو کال میکنید ؟

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
/api/v1/profile/edit_me/
/api/v1/profile/me

**Comment by PouryaMansouri** [comment]
تو بک ایشو رو میشه بزنید

**Comment by milad7212** [comment]
این ایشو با تغییر در بک درست شده و نیاز به تغییری از سمت فرانت نبوده .
