### ISSUE TITLE
آپدیت تصویر پروفایل حجره

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#64]
زمانی که دو حجره داشته باشیم و حجره انتخابی را عوض کنیم، هنوز تصویر پروفایل حجره قبلی نمایش داده می شود (عکس پروفایل حجره به موقع آپدیت نمی شود.)

**Comment by milad7212** [comment]
@MaryamSamareh 
خانم هاشمی این مورد حل شده است .لطفا بررسی بفرمایید اگر ایراد رفع شده بود این تسک را ببندید.
با تشکر

**Comment by MaryamSamareh** [comment]
done
