### ISSUE TITLE
نمایش اندازه محصول

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#65]
در بخش ثبت محصول، قسمتی برای وارد کردن اندازه محصول نداریم اما در صفحه جزئیات، سایز محصول هم نمایش داده می شود.

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh دلیل این مساله این هست که دو طراحی کاملا متفاوت در سایت مورد پیاده سازی قرار گرفته است.

**Comment by likecodingloveproblems** [comment]
@milad7212 @sahar-shafiee

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh در نظر داشته باشید ابعاد محصول در روش و هزینه ارسال تاثیرگذار خواهد بود.

**Comment by MaryamSamareh** [comment]
> @MaryamSamareh در نظر داشته باشید ابعاد محصول در روش و هزینه ارسال تاثیرگذار خواهد بود.

درسته ولی الان که دیگه این گزینه رو در ایجاد محصول نداریم. و منظور من هم این بود که اگه محصولی داریم که اندازه اش وارد نشده و صفر هست، اصلا این مقدار صفر به کاربر نمایش داده نشه

**Comment by milad7212** [comment]
این ویژگی در برنچ 73 افزوده شد
