### ISSUE TITLE
عدم نمایش ناموجود بدون محصول روی کارت محصول

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_frontend#66]
![2باگ نمایش ندادن آرم ناموجود بودن](https://user-images.githubusercontent.com/52815608/169967667-dc00e021-8162-4c12-ad82-28a107ef635b.png)
![باگ نمایش ندادن آرم ناموجود بودن](https://user-images.githubusercontent.com/52815608/169967679-74a9147d-28da-4bac-bcc6-e5427b9c3cef.png)

این محصول با اینکه ناموجود هست ولی روی کارت محصول ناموجود بودن نمایش داده نمی شود

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh have you any idea of how to show this to user?

**Comment by MaryamSamareh** [comment]
> @MaryamSamareh have you any idea of how to show this to user?
ایده ای به جز غیرفعال کردن دکمه خرید؟
به نظر من بهترین راه همونه که دکمه افزودن به سبد خرید تبدیل به ناموجود میشه.

**Comment by milad7212** [comment]
با سلام چک شد . و در سایت  به درستی کار میکنه 
ایرادی که اینجا نشان داده شده . این است که در صفحه لندینگ  از وقتی که محصول موجود بوده  ساخته شده و بصورت استاتیکی هست .برای اینکه  این مورد  پیش نیاید میتوان در بازه زمانی کمتر   صفحه لندینگ حجره  را به روزرسانی کنند

**Comment by sahar-shafiee** [comment]
https://github.com/nakhll-company/nakhll_backend/issues/136
این ایشو نیاز به تغییرات در سمت بک دارد که ایشو مورد نظر در سمت بک ایجاد شده است

**Comment by milad7212** [comment]
@sahar-shafiee سمت فرانت هم باید کل ساختار لایو ادیت تغییر کند. که تغییر نسبتا زیادی هست .هزینه پیاده سازیش از لحاظ زمانی بالاس. بنظرم مشورت بشه بعد تسکش ایجاد شود بهتره .که ایا بیزینس نیاز به همچین تغییری را میخواهد

**Comment by sahar-shafiee** [comment]
@milad7212
ایشو این مسئله سمت بک زده شده با پایین ترین الویت در صورتی که تسک با الویت بالایی وجود نداشته باشه میشه روی این تسک وقت گذاشت و روی خود ایشو همه می توانند نظر بدهند
در صورتی که مخالفتی با انجام تسک باشه میشه ایشو رو بست

**Comment by milad7212** [comment]
this issue is not a bug please change label

**Comment by milad7212** [comment]
این موضوع باگ نیست ساختاریه که از قبل توافق شده بود. بنده این موضوع را میبندم در صورتی که بیزینس خواست به عنوان فیچر باز شود.
