### ISSUE TITLE
خطای صفحه سرچ

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_frontend#73]
![Capture](https://user-images.githubusercontent.com/52815608/170422163-848bcab4-d451-48b3-a522-c16c94152c49.JPG)
@milad7212

**Comment by milad7212** [comment]
در ای پی ای state بصورت ابجکت تغییر کرده و این منجر به ایجاد خطا شده است . در استانه برطرف شدند

**Comment by sahar-shafiee** [comment]
@milad7212 
روی این پول ریکئوست هم خطای صفحه سرچ برطرف شده و هم صفحه حجره؟

**Comment by milad7212** [comment]
@sahar-shafiee بله
