### ISSUE TITLE
خطای افزودن لینک در ایجاد صفحه فرود اختصاصی

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_frontend#78]
بعد از ایجاد یک لینک از تمامی محصولات
در صفحه ایجاد صفحه فرود اختصاصی با اساین کردن لینک مورد نظر با خطای 500 مواجه شدیم

**Comment by milad7212** [comment]
فقط تمامی محصولات این اتفاق می افته براش؟
@sahar-shafiee

**Comment by milad7212** [comment]
![localhost_3007_](https://user-images.githubusercontent.com/25881604/171121997-7bc259d0-d6ad-44db-a56b-3fb2bcef0c87.png)
@sahar-shafiee 

i don't access to this page

**Comment by milad7212** [comment]
این موضوع حل شده
