### ISSUE TITLE
بخش بالای سایت

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#89]
در سایز 767 پیکسل کلا بخش بالای سایت حذف می شود و فقط قسمت های فیلترها و مرتب سازی از نوار بالای سایت باقی می ماند که آنها هم کار نمی کنند.
در سایز 1200 تا 767 پیکسل لیست دسته بندی ها (نوار اصلی بالای سایت) هم نمایش داده نمی شود.

**Comment by milad7212** [comment]
done
