### ISSUE TITLE
نمایش ندادن فروشنده محصول در حالت موبایل

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#93]
در صفحه محصول در حالت تلفن همراه، فروشنده محصول نمایش داده نمی شود.
گزینه بازگشت به صفحه قبل نداریم و حتما باید از کلید back مرورگر استفاده شود.

**Comment by milad7212** [comment]
@MaryamSamareh  
فروشنده محصول نمایش داده می شود .
