### ISSUE TITLE
فیلتر حجره

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#96]
زمانی که محصولی را در سایت جستجو می کنیم و فیلتر حجره روی آن قرار می دهیم، تمام محصولات حجره انتخاب شده را نمایش می دهد اما اگر از نوار دسته بندی، دسته بندی خاصی را انتخاب کنیم فقط محصولاتی که در آن حجره همان دسته بندی را دارند نمایش می دهد. (روند اجرا:
جستجو در نخل -> جستجو بر اساس حجره -> نمایش تمام محصولات حجره انتخاب شده
انتخاب دسته بندی خاصی مثلا ادویه و چاشنی ها -> جستجو بر اساس حجره -> فقط نمایش محصولاتی از حجره که در این دسته بندی قرار دارند )

**Comment by milad7212** [comment]
@MaryamSamareh

**Comment by milad7212** [comment]
@likecodingloveproblems  
@MaryamSamareh 
لطفا بررسی بفرمایید.

**Comment by milad7212** [comment]
@MaryamSamareh 
خانم هاشمی این تسک را  بررسی میفرمایید.  ساختار نیاز به تغییر دارد ؟

**Comment by MaryamSamareh** [comment]
@milad7212 
فکر میکنم این تسک در نظر من اشکال بوده اما به طور کلی سیاست های پیاده سازی به همین صورت بوده و نیاز به تغییر ندارد. 
درنتیجه با تشکر از پیگیری شما، من این تسک را می بندم
