### ISSUE TITLE
امکان جستجو بین استان و شهر

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_frontend#98]
امکان جستجو بین استان و شهر حجره دار در سایت وجود ندارد. (به دلیل طولانی بودن لیست استان و شهر ها، اگر امکان سرچ بین آنها وجود داشته باشد یا به ترتیب الفبایی چیده شوند، دسترسی به آنها راحت تر خواهد بود)

**Comment by milad7212** [comment]
انجام شد به ترتیب حروف الفبا مرتب شد
